name: CI win_d

on:
  push:
    branches:    
      - master
jobs:
  build:

    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        cd code; ./fips build win_d
    - name: Show CMakeOutput.log
      if: failure()
      run: cat cpp/trunk/fips-build/code/windows/CMakeFiles/CMakeOutput.log
    - name: Show CMakeError.log
      if: failure()
      run: cat cpp/trunk/fips-build/code/windows/CMakeFiles/CMakeError.log
    